version: '3.7'

services:
  web:
    build:
      context: . # 上下文目录
      dockerfile: ./deployments/Dockerfile # Dockerfile文件
      args:
        TARGETGOOS: "linux"
        TARGETARCH: "amd64"
    image: "hello-go"
    restart: always
    ports:
      - "8080:8080"
    environment:
      TZ: Asia/Shanghai
    networks:
      - hello-go
  mysql:
    build: ./deployments/mysql
    container_name: "mysql"
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      # TZ: "Etc/GMT+5" #"America/New_York"
    volumes:
      - ./deployments/mysql/data:/var/lib/mysql
      - ./deployments/mysql/conf.d:/etc/mysql/conf.d
    networks:
      - hello-go
  phpmyadmin:
    image: "phpmyadmin:latest"
    container_name: "phpmyadmin"
    restart: always
    ports:
      - "8888:80"
    volumes:
      - ./deployments/phpmyadmin/config.inc.php:/etc/phpmyadmin/config.user.inc.php
    environment:
      - PMA_ARBITRARY=1
    networks:
      - hello-go
networks:
  hello-go:
    driver: bridge